### ISSUE TITLE
无法正确获取 

### ISSUE THREAD

**Issue by muxik** [dnmkrgi/xi-speech-synthesizer#6]
```json
{
   "text": "世界人民大团结万岁"
}

```

```json
{
    "message": "文本缺失",
    "request_successful": false
}
```

求解

**Comment by dnmkrgi** [comment]
请确保你的request header中Content-Type是application/json

**Comment by muxik** [comment]
在我更新了python后遇到了如下问题
```
Traceback (most recent call last):
  File "api.py", line 9, in <module>
    from database import delete_item, get_result, get_progress, set_result, create_item, set_progress
  File "/home/muxik/github/xi-speech-synthesizer/database.py", line 2, in <module>
    from api import app
  File "/home/muxik/github/xi-speech-synthesizer/api.py", line 9, in <module>
    from database import delete_item, get_result, get_progress, set_result, create_item, set_progress
ImportError: cannot import name 'delete_item' from partially initialized module 'database' (most likely due to a circular import) (/home/muxik/github/xi-speech-synthesizer/database.py)

```

Python版本
```
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Archlinux
